---
title: "Exploratory Data Analysis"
author: "David LeBauer"
date: "5/30/2017"
output:
  html_document: default
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## Load biofuel data from betydb.org

```{r load-data, message=FALSE, }
salix <- read_csv('data/salix.csv')
```
```{r load-data-loop, message=FALSE}
all_genera <- list()
for(genus in c('salix', 'panicum', 'miscanthus', 'populus')){
  all_genera[[genus]] <- read_csv(paste0('data/', genus, '.csv'))
  
  all_genera[[genus]]$mean <- as.numeric(all_genera[[genus]]$mean)
}
all_genera_df <- dplyr::bind_rows(all_genera)
```


## Load Sorghum data from terraref.ncsa.illinois.edu/bety

```{r db-connection}
library(RPostgreSQL)

dbcon <- dbConnect(RPostgreSQL::PostgreSQL(),
                dbname = "bety", 
                password = 'bety', 
                host = 'terra-bety.default', 
                user = 'bety', 
                port = 5432)

```


```{sql basic-query, connection = dbcon}
select variables.name, mean 
  from traits join variables 
  on traits.variable_id = variables.id
  limit 10;

```

```{sql trait-counts, connection = dbcon}
select variables.name, count(*) as n 
  from traits join variables 
  on traits.variable_id = variables.id
  group by variables.name
  order by n desc;

```


```{r}
library(dplyr)

bety_src <- src_postgres(dbname = "bety", 
                password = 'bety', 
                host = 'terra-bety.default', 
                user = 'bety', 
                port = 5432)

traits <- tbl(bety_src, 'traits')

variables <- tbl(bety_src, 'variables') %>% 
  mutate(variable_id = id)

traits_variables <- traits %>% 
  left_join(variables, by = 'variable_id') %>% 
  select(name, mean) %>% 
  collect

dim(traits_variables)
head(traits_variables)

traitsview <- tbl(bety_src, 'traits_and_yields_view')

dim(traitsview)
```



### How to get at managements

Here we are using the traits package to access the betydb.org website


```{r query-mgmts, cache=TRUE}
library(traits)
library(dplyr)

options(#betydb_key = readLines('~/.betykey', warn = FALSE),
        betydb_url = "https://betydb.org",
        betydb_api_version = 'beta')

species <- betydb_query(table = 'species', limit = 'none') %>% 
  mutate(specie_id = id)

sites <- betydb_query(table = 'sites', limit = 'none') %>% 
  mutate(site_id = id)

yields <- betydb_query(table = 'yields', limit = 'none') %>%
  select(id, date, mean, n, statname, stat, site_id, specie_id, treatment_id, citation_id, cultivar_id) %>% 
  left_join(species, by = 'specie_id') %>%
  left_join(sites, by = 'site_id') 

managements_treatments <- #tbl(bety, 'managements_treatments') %>%
  betydb_query(table = 'managements_treatments') %>% 
  select(treatment_id, management_id)

treatments <- betydb_query(table = 'treatments') %>% 
  dplyr::mutate(treatment_id = id) %>% 
  dplyr::select(treatment_id, name, definition, control)

managements <- betydb_query(table = 'managements') %>%
  filter(mgmttype %in% c('fertilizer_N', 'fertilizer_N_rate', 'planting', 'irrigation')) %>%
  dplyr::mutate(management_id = id) %>%
  dplyr::select(management_id, date, mgmttype, level, units) %>%
  left_join(managements_treatments, by = 'management_id') %>%
  left_join(treatments, by = 'treatment_id') 


nitrogen <- managements %>% 
  filter(mgmttype == "fertilizer_N_rate") %>%
  select(treatment_id, nrate = level)

planting <- managements %>% filter(mgmttype == "planting") %>%
  select(treatment_id, planting_date = date)

planting_rate <- managements %>% filter(mgmttype == "planting") %>%
  select(treatment_id, planting_date = date, planting_density = level) 

irrigation <- managements %>% 
  filter(mgmttype == 'irrigation') 

irrigation_rate <- irrigation %>% 
  filter(units == 'mm', !is.na(treatment_id)) %>% 
  group_by(treatment_id, year = sql("extract(year from date)"), units) %>% 
  summarise(irrig.mm = sum(level)) %>% 
  group_by(treatment_id) %>% 
  summarise(irrig.mm.y = mean(irrig.mm))

irrigation_boolean <- irrigation %>%
  collect %>%   
  group_by(treatment_id) %>% 
  mutate(irrig = as.logical(mean(level))) %>% 
  select(treatment_id, irrig = irrig)

irrigation_all <- irrigation_boolean %>%
  full_join(irrigation_rate, copy = TRUE, by = 'treatment_id')

grass_yields <- yields %>% 
  filter(genus %in% c('Miscanthus', 'Panicum')) %>%
  left_join(nitrogen, by = 'treatment_id') %>% 
  #left_join(planting, by = 'treatment_id') %>% 
  left_join(planting_rate, by = 'treatment_id') %>% 
  left_join(irrigation_all, by = 'treatment_id', copy = TRUE) %>% 
  collect %>% 
  mutate(age = year(date)- year(planting_date),
         nrate = ifelse(is.na(nrate), 0, nrate),
         SE = ifelse(statname == "SE", stat, ifelse(statname == 'SD', stat / sqrt(n), NA)),
         continent = ifelse(lon < -30, 'united_states', ifelse(lon < 75, 'europe', 'asia'))) %>% 
  filter(!duplicated(.))

```